server:
  port: 8080

kenect-labs:
    url: "https://candidate-challenge-api-489237493095.us-central1.run.app/api/v1/contacts"
    token: "J7ybt6jv6pdJ4gyQP9gNonsY"
    pageCounterHeaderName: "total-pages"
